### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by mschilling** [mschilling/super-tv-guide#33]
Would be nice to be able to set a reminder for an upcoming show.

Reminders should trigger a (local or server based) push notification.

This will help the user NOT to miss a show :-)

**Comment by yoshschoemaker** [comment]
Het is (zover ik gevonden heb) niet mogelijk om reminders te zetten via de pwa zelf. De pwa kan zelf niet in de background actief blijven om te kijken of het al tijd is om de reminder te sturen, en dit is ook niet mogelijk via google cloud functions (wél voor iOS en android, niet voor pwa's).

Als oplossing zouden we een knop kunnen maken waarmee je het item toevoegt aan je google calendar, met een reminder (wat ongeveer al het originele idee was), of er moet server based iets gebeuren.
